import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/_components/Navbar";
import { getCurrentUser } from "@/_lib/actions/user.actions";
import { VoyagerProvider } from "./voyagerContext";
import "react-datepicker/dist/react-datepicker.css";
import { ColorModeProvider } from "./colorModeContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ColorModeProvider>
          <VoyagerProvider>
            <section className="flex flex-col bg-gray-100 dark:bg-gray-900 dark:text-slate-100 min-h-dvh">
              <Navbar user={user} />
              {children}
            </section>
          </VoyagerProvider>
        </ColorModeProvider>
      </body>
    </html>
  );
}
